# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('updated_at', models.DateTimeField(verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
