# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='background_color',
            field=models.CharField(default='#A0BBE4', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='foreground_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
    ]
