# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170911_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='card',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(default='#A0BBE4', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='foreground_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
