# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170911_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
