# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170911_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Deck'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
