# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170912_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='card',
            name='foreground_color',
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(max_length=200),
        ),
    ]
