# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170913_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pos',
            field=models.IntegerField(null=True),
        ),
    ]
