# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_card_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
