# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170914_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pos',
        ),
    ]
